# -*- coding: utf-8 -*-
"""Sentimental_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qma6lToj0rtOMTGok1rgfwYTtWzZh5_s
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use ('ggplot')
import nltk

df=pd.read_csv('Reviews.csv')

df.shape

df=df.head(500)
df.head()

"""**Quick EDA**"""

ax = df['Score'].value_counts().sort_index() \
    .plot(kind='bar',
          title='Count of Reviews by Stars',
          figsize=(10, 5))
ax.set_xlabel('Review Stars')
plt.show()

"""Basic NLTK"""

example = df['Text'][1]
print(example)
#this will give me the text of 1st row

import nltk

# Download the 'punkt' resource
nltk.download('punkt')

tokens = nltk.word_tokenize(example)
print(tokens[:10])

import nltk

# Download the 'punkt' resource
nltk.download('punkt')
# Download the 'averaged_perceptron_tagger' resource
nltk.download('averaged_perceptron_tagger')

tokens = nltk.word_tokenize(example)
print(tokens[:10])

# assigns a part of speech (POS) to each token, identifying it as a noun, verb, etc.
tagged = nltk.pos_tag(tokens)

tagged[:10]

# attempts to identify named entities, such as names or locations.
import nltk

# Download the necessary resources
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words') # Download the missing 'words' dataset

tokens = nltk.word_tokenize(example)
tagged = nltk.pos_tag(tokens)

# Now, the named entity chunking should work
entities = nltk.chunk.ne_chunk(tagged)
entities.pprint()

"""Step 1. VADER Seniment Scoring¶ We will use NLTK's SentimentIntensityAnalyzer to get the neg/neu/pos scores of the text.

This uses a "bag of words" approach:

1.Stop words are removed

2.each word is scored and combined to a total score.
"""

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

import nltk
nltk.download('vader_lexicon') # Download the missing 'vader_lexicon' dataset

sia = SentimentIntensityAnalyzer()

sia.polarity_scores('I am so happy!')

# Run the polarity score on the entire dataset
# VADER Sentiment Analysis on the Whole Dataset
res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
    text = row['Text']
    myid = row['Id']
    res[myid] = sia.polarity_scores(text)

vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns={'index': 'Id'})
vaders = vaders.merge(df, how='left')

# Now we have sentiment score and metadata
vaders.head()

ax = sns.barplot(data=vaders, x='Score', y='compound')
ax.set_title('Compund Score by Amazon Star Review')
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(12, 3))
sns.barplot(data=vaders, x='Score', y='pos', ax=axs[0])
sns.barplot(data=vaders, x='Score', y='neu', ax=axs[1])
sns.barplot(data=vaders, x='Score', y='neg', ax=axs[2])
axs[0].set_title('Positive')
axs[1].set_title('Neutral')
axs[2].set_title('Negative')
plt.tight_layout()
plt.show()

"""Step 3. Roberta Pretrained Model
->Use a model trained of a large corpus of data.

->Transformer model accounts for the words but also the context related to other words.
"""

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

#  pretrained RoBERTa model (twitter-roberta-base-sentiment) and its tokenizer from Hugging Face’s Transformers library.
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

# VADER results on example
print(example)
sia.polarity_scores(example)

# Run for Roberta Model
encoded_text = tokenizer(example, return_tensors='pt')
output = model(**encoded_text)
scores = output[0][0].detach().numpy()
scores = softmax(scores)
scores_dict = {
    'roberta_neg' : scores[0],
    'roberta_neu' : scores[1],
    'roberta_pos' : scores[2]
}
print(scores_dict)

def polarity_scores_roberta(example):
    encoded_text = tokenizer(example, return_tensors='pt')
    output = model(**encoded_text)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    scores_dict = {
        'roberta_neg' : scores[0],
        'roberta_neu' : scores[1],
        'roberta_pos' : scores[2]
    }
    return scores_dict

# Running RoBERTa on the Entire Dataset
res = {}
for i, row in tqdm(df.iterrows(), total=len(df)):
    try:
        text = row['Text']
        myid = row['Id']
        vader_result = sia.polarity_scores(text)
        vader_result_rename = {}
        for key, value in vader_result.items():
            vader_result_rename[f"vader_{key}"] = value
        roberta_result = polarity_scores_roberta(text)
#         both VADER and RoBERTa to each review and stores the combined scores.
        both = {**vader_result_rename, **roberta_result}
        res[myid] = both
    except RuntimeError:
        print(f'Broke for id {myid}')

# prompt: i want to analyse the sentiment single example on the basis of Robert model

example = "This is a great product! I am very happy with it."

encoded_text = tokenizer(example, return_tensors='pt')
output = model(**encoded_text)
scores = output[0][0].detach().numpy()
scores = softmax(scores)  # softmax is applied to the scores to convert them into probabilities, ensuring they sum to 1.
scores_dict = {
    'roberta_neg' : scores[0],
    'roberta_neu' : scores[1],
    'roberta_pos' : scores[2]
}
scores_dict

# prompt: can i get the analysis of the  Running RoBERTa on the Entire Dataset which would be positive ,negative  and neutral

results_df = pd.DataFrame(res).T.reset_index().rename(columns={'index': 'Id'})
results_df = results_df.merge(df, how='left')

# Analyze the sentiment distribution for each category (positive, negative, neutral)
# using RoBERTa scores

def get_sentiment_label(row):
  """
  Determines the sentiment label based on the RoBERTa scores.
  """
  if row['roberta_pos'] > row['roberta_neg'] and row['roberta_pos'] > row['roberta_neu']:
    return 'Positive'
  elif row['roberta_neg'] > row['roberta_pos'] and row['roberta_neg'] > row['roberta_neu']:
    return 'Negative'
  else:
    return 'Neutral'


results_df['sentiment_label'] = results_df.apply(lambda row: get_sentiment_label(row), axis=1)

# Analyze the distribution of sentiment labels
sentiment_counts = results_df['sentiment_label'].value_counts()
print(sentiment_counts)

# Visualize the sentiment distribution using a bar chart or pie chart
plt.figure(figsize=(8, 6))
plt.bar(sentiment_counts.index, sentiment_counts.values)
plt.xlabel('Sentiment')
plt.ylabel('Count')
plt.title('Sentiment Distribution (RoBERTa)')
plt.show()

# Further analysis can include:
# - Comparing sentiment scores between RoBERTa and VADER
# - Exploring the relationship between sentiment and other features (e.g., star rating)
# - Analyzing the most positive/negative reviews
# - Identifying potential biases in the model's predictions

# prompt: i want totally new example other than given in the dataset , pich one random example and  give me output which where does it lie positive negative or netral

import random
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Assuming you have the 'vaders' DataFrame from your previous code
# ... (Your code to load the 'vaders' DataFrame) ...

# Choose a random example from the DataFrame
random_example_index = random.randint(0, len(vaders) - 1)
random_example = vaders.iloc[random_example_index]

# Extract the text and sentiment scores
text = random_example['Text']
compound_score = random_example['compound']

# Print the example text and its sentiment
print("Example Text:")
print(text)

# Classify sentiment based on compound score
if compound_score >= 0.05:
    sentiment = "Positive"
elif compound_score <= -0.05:
    sentiment = "Negative"
else:
    sentiment = "Neutral"

print(f"Sentiment: {sentiment}")

